Improve documentation
miracl/oidc-samples pull request #71
Opened 2024-12-27 11:53 UTC by tatiNo5

2025-01-02 07:25 UTC, Foriger commented on samples/dotnet/README.md
> +
Don't think we need two new rows.

2025-01-06 11:04 UTC, tatiNo5 commented on samples/dotnet/README.md
> +
fixed

2025-01-07 12:43 UTC, VMitov requested changes

2025-01-07 12:43 UTC, VMitov commented on README.md
> +of the client library.
What integration test suite?

2025-01-08 08:36 UTC, ZSPASOV commented on integration-tests/README.md
> +The `Redirect URL` must be the same as the one the testing sample is run with.
Should we change Redirect URL to REDIRECT_URL, the name of the env variable.

2025-01-08 08:40 UTC, ZSPASOV commented on README.md
>  information of the proxied requests.
Maybe in the main README file we can give an example what the final output response should look like, after we do all the steps.

2025-01-08 14:41 UTC, ZSPASOV approved these changes

2025-01-08 16:23 UTC, VMitov requested changes
For the usage of the main README:

## Usage

You can start every sample with its native tooling. For instructions, see the
README.md of the sample you are interested in.

Once you start your sample of choice, go to http://localhost:8000, which will
take you to the MIRACL Trust authorization page. You need to enrol the device
the first time you use the sample. Afterwards, you can authenticate directly
using MPIN.

### Run with Docker

You can also use Docker to run any sample.

### Run on a different port with Docker

All samples use port 8000 as the default; hence, the sample starts at 8000, and
the default OIDC Redirect URL is `http://localhost:8000/login`. To change the
port you access the sample on, do the following:

```bash
docker run -it \
  --publish <custom-port>:8000 \
  --env CLIENT_ID=<client-id> \
  --env CLIENT_SECRET=<client-secret> \
  --env REDIRECT_URL=http://localhost:<custom_port>/login \
  sample
```

Note that we don't need to change the port the sample runs on in the container -
just the Docker mapping. The redirect URL must also be updated in
the command and the configuration in the [MIRACL Trust
portal](https://trust.miracl.cloud).

2025-01-09 08:29 UTC, VMitov requested changes

2025-01-09 08:29 UTC, VMitov commented on samples/go/README.md
> +go run . -client-id <client-id> -client-secret <client-secret>
```suggestion
go run . \
    -client-id <client-id> \
    -client-secret <client-secret>
```

2025-01-09 08:29 UTC, VMitov commented on samples/go/README.md
> +info is presented.
```suggestion
This starts the sample HTTP server. When you access http://localhost:8000/, you
will be directed to the MIRACL Trust authorization page to begin the
registration and authentication process. After successful authentication, the
sample retrieves the OIDC UserInfo endpoint and returns the result.
```

2025-01-09 08:29 UTC, VMitov commented on samples/go/README.md
> +the latter, follow the instructions [here](../../README.md).
If I understand the difference between "Setup" and "Usage", this section should be in the following. 

P.S. I still think "Run with docker" should be a separate section at the end.

2025-01-09 08:29 UTC, VMitov commented on samples/go/README.md
> +to integrate with the MIRACL Trust platform.
The OIDC client library is the most important information here. I don't think we should hide it under "Dependencies".

2025-01-09 17:43 UTC, VMitov commented on samples/go/README.md
> +variables as follows:
Isn't that obsolete?

2025-01-09 17:46 UTC, VMitov requested changes

2025-01-09 17:46 UTC, VMitov commented on samples/python/README.md
> +```
Those are not used.

2025-01-09 17:46 UTC, VMitov commented on samples/python/README.md
> +    --client-secret CLIENTSECRET
Lets have placeholders formatted the same across all files

2025-01-09 17:58 UTC, VMitov approved these changes

2025-01-13 08:39 UTC, ZSPASOV approved these changes

2025-01-13 08:42 UTC, merged